openapi: 3.0.3
info:
  title: NBM Payment Hub API Gateway
  description: Documentation to integrate with NBM Payment Hub for third-party services.
  version: 1.0.0
servers:
  - url: https://moneyconnect.natbankmw.com/v1
    description: Base URL for NBM Payment Hub

paths:
  /:
    get:
      summary: Root Endpoint
      description: Welcome message for the API.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to the NBM Payment Hub API Gateway."
  /auth/token:
    post:
      summary: Generate Access Token
      description: Obtain an access token for authentication with the API.
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - clientId
                - clientSecret
              properties:
                clientId:
                  type: string
                  description: Client ID provided by the bank.
                clientSecret:
                  type: string
                  description: Client Secret provided by the bank.
            example:
              clientId: "C87stk86mED2qG7kFZRwSuady"
              clientSecret: "pkAV1p9DqBXsBhbWh8bacCNiyTYCmJX3"
      responses:
        '200':
          description: Token generated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: The generated access token.
                  expires_in:
                    type: integer
                    description: Time in seconds before the token expires.
                example:
                  access_token: "eyJhbGciOiJSUzI1NjYWZl..."
                  expires_in: 300
        '400':
          description: Invalid request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid client credentials provided."
        '500':
          description: Server error.
    
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized. Please provide a valid Bearer token."

  /api/{account_number}:
    get:
      summary: Get Account Information
      description: Retrieve details about an account.
      parameters:
        - name: account_number
          in: path
          required: true
          schema:
            type: string
          description: The account number to be validated.
      responses:
        '200':
          description: Account information retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Success"
                  data:
                    type: object
                    properties:
                      account_number:
                        type: string
                      customer_number:
                        type: string
                      category:
                        type: string
                      branch:
                        type: string
                      currency:
                        type: string
                      locked_amount:
                        type: string
                      limit_amount:
                        type: string
                    example:
                      account_number: "100100200"
                      customer_number: "424082"
                      category: "Saving Ord"
                      branch: "Zomba"
                      currency: "MWK"
                      locked_amount: "0.00"
                      limit_amount: "0.00"
        '404':
          description: Account not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Account not found."
        '401':
          description: Unauthorized.
        '500':
          description: Server error.

  /api/transfer:
    post:
      summary: Send Funds
      description: Push funds to an account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reference
                - credit_account
                - currency
                - amount
                - description
              properties:
                reference:
                  type: string
                  description: Reference for the transaction.
                credit_account:
                  type: string
                  description: Account to credit.
                currency:
                  type: string
                  description: Currency of the transaction.
                amount:
                  type: number
                  format: double
                  description: Amount to transfer.
                description:
                  type: string
                  description: Description of the transaction.
            example:
              reference: "INV/2003/202930"
              credit_account: "632481"
              currency: "MWK"
              amount: 25361.23
              description: "Test transaction"
      responses:
        '200':
          description: Funds transferred successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Success"
                  data:
                    type: object
                    properties:
                      reference:
                        type: string
                        description: Transaction reference.
                    example:
                      reference: "FT24928459824"
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid account details."
        '500':
          description: Server error.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  responses:
    UnauthorizedError:
      description: Invalid or expired access token.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Authentication error."
security:
  - BearerAuth: []
